server:
  port: 8080

spring:
  application:
    name: gateway-server
  devtools:
    restart:
      enabled: false
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/main?useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: qrka66EDOYsxKyrIVOKhSh6CzC2kFFCJdHeIA9QwfzTdh6oPzakT1dM3FMr2NMs0GdOf9dHB1QloynSG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    gateway-server: DEBUG
