server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/main?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
