#server:
#  port: 8084
#
#spring:
#  application:
#    name: customer-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/main?useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          format_sql: true
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#jwt:
#  secret: qrka66EDOYsxKyrIVOKhSh6CzC2kFFCJdHeIA9QwfzTdh6oPzakT1dM3FMr2NMs0GdOf9dHB1QloynSG
#  expiration: 259200
#
#logging:
#  level:
#    customer-service: DEBUG
